package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Doom theme
 * Original color scheme by LuftVerbot
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary 0xFFF38020
 * Secondary 0xFFF38020
 * Tertiary 0xFF1B1B22
 * Neutral 0xFF655C5A
 */
internal object DoomColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFB4B4),
        onPrimary = Color(0xFF690000),
        primaryContainer = Color(0xFF93000A),
        onPrimaryContainer = Color(0xFFFFDAD6),
        inversePrimary = Color(0xFF6D0D0B),
        secondary = Color(0xFFFFB4B4),
        onSecondary = Color(0xFF690000),
        secondaryContainer = Color(0xFF93000A),
        onSecondaryContainer = Color(0xFFFFDAD6),
        tertiary = Color(0xFFBFBFBF),
        onTertiary = Color(0xFF1B1B1B),
        tertiaryContainer = Color(0xFF424242),
        onTertiaryContainer = Color(0xFFDADADA),
        background = Color(0xFF1B1B1B),
        onBackground = Color(0xFFFFFFFF),
        surface = Color(0xFF1B1B1B),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF303030),
        onSurfaceVariant = Color(0xFFDADADA),
        surfaceTint = Color(0xFFFFB4B4),
        inverseSurface = Color(0xFFFAFAFA),
        inverseOnSurface = Color(0xFF313131),
        outline = Color(0xFF8F9099),
        outlineVariant = Color(0xFF44464F),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFFB3261E),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDAD6),
        onPrimaryContainer = Color(0xFF410002),
        inversePrimary = Color(0xFF6D0D0B),
        secondary = Color(0xFFB3261E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDAD6),
        onSecondaryContainer = Color(0xFF410002),
        tertiary = Color(0xFF7A5760),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD9DE),
        onTertiaryContainer = Color(0xFF31101A),
        background = Color(0xFFFEFBFF),
        onBackground = Color(0xFF1B1B1B),
        surface = Color(0xFFFEFBFF),
        onSurface = Color(0xFF1B1B1B),
        surfaceVariant = Color(0xFFF3EDF7),
        onSurfaceVariant = Color(0xFF49454E),
        surfaceTint = Color(0xFFB3261E),
        inverseSurface = Color(0xFF313033),
        inverseOnSurface = Color(0xFFF4EFF4),
        outline = Color(0xFF757780),
        outlineVariant = Color(0xFFC5C6D0),
    )
}
